spring:
  datasource:
    url: jdbc:tc:postgresql:13.2://localhost/mydb
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
